pipeline {
    agent any

    environment {
        APP_NAME = "express-frontend"
        BACKEND_URL = "http://localhost:5000"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Node Dependencies') {
            steps {
                dir('frontend') {
                    sh 'npm install'
                }
            }
        }

        stage('Start Express Frontend') {
            steps {
                dir('frontend') {
                    sh '''
                    pm2 delete $APP_NAME || true
                    BACKEND_URL=$BACKEND_URL pm2 start server.js --name $APP_NAME
                    pm2 save
                    '''
                }
            }
        }
    }
}
