pipeline {
    agent any

    environment {
        APP_NAME = "express-app"
        BACKEND_URL = "http://localhost:5000"
    }

    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Start Express App') {
            steps {
                sh '''
                pm2 delete $APP_NAME || true
                BACKEND_URL=$BACKEND_URL pm2 start server.js --name $APP_NAME
                pm2 save
                '''
            }
        }
    }
}
