pipeline {
    agent any
    environment {
        VENV = "/home/ubuntu/Assignment_9/backend/venv"
    }
    stages {
        stage('Activate Virtualenv & Start Flask') {
            steps {
                dir('backend') {
                    sh """
                    # Activate virtualenv
                    source $VENV/bin/activate
                    
                    # Start or restart Flask using PM2
                    pm2 restart flask-app || pm2 start app.py --name flask-app --interpreter $VENV/bin/python
                    """
                }
            }
        }
    }
}

