pipeline {
    agent any
    environment {
        VENV = "/home/ubuntu/Assignment_8/backend/venv"
    }
    stages {
        stage('Activate Virtualenv') {
            steps {
                dir('backend') {
                    sh """
                    source $VENV/bin/activate
                    pip install -r requirements.txt
                    pm2 restart flask-app || pm2 start app.py --name flask-app --interpreter $VENV/bin/python
                    """
                }
            }
        }
    }
}

