pipeline {
    agent any

    environment {
        APP_NAME = "flask-backend"
        VENV = "venv"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Python Dependencies') {
            steps {
                dir('backend') {
                    sh '''
                    python3 -m venv $VENV
                    $VENV/bin/pip install --upgrade pip
                    $VENV/bin/pip install -r requirements.txt
                    '''
                }
            }
        }

        stage('Start Flask Backend') {
            steps {
                dir('backend') {
                    sh '''
                    pm2 delete $APP_NAME || true
                    pm2 start app.py \
                      --name $APP_NAME \
                      --interpreter $VENV/bin/python
                    pm2 save
                    '''
                }
            }
        }
    }
}
